spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://127.0.0.1:1433;DatabaseName=testdb;encrypt=true;trustServerCertificate=true
    username: rms
    password: rms

  jpa:
    show-sql: true

  mvc:
    hidden-method:
      filter:
        enabled: true

  thymeleaf:
    cache: false
#  main:
#    allow-circular-references: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
#logging:
#  level:
#    root: debug